development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: beka_development
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock

# Attention: The database defined as "test" will *not* be erased and
# re-generated on every "rake" run. It is safe to set this db to the same as
# development or production for testing.
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: beka_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: beka_production
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock
